export enum Provider {
  MONGODB_CONNECTION = 'MONGODB_CONNECTION',
  MONGODB_CONNECTION_TEST = 'MONGODB_CONNECTION_TEST',
  CUSTOMER_MODEL = 'CUSTOMER_MODEL',
  PRODUCT_MODEL = 'PRODUCT_MODEL',
  PURCHASE_MODEL = 'PURCHASE_MODEL',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  PRODUCT_SERVICE = 'PRODUCT_SERVICE'
}
